#!/bin/sh

declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
	echo "";
else
	if [ $(dpkg-query -W -f='${Status}' mobilesubstrate 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
		echo "";
		echo "MISSING DEPENDENCIES.";
		echo 'PLEASE INSTALL "Cydia Substrate" (formerly "Mobile Substrate")!';
		echo "";
	fi
fi

exit 0
